name: Automatic Website Deployment 

on:
  push:
   branches:
    - main
jobs:
  deploy:
    run-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Website
        run: |
          sudo cp -r ./* /var/www/website/
